### PR TITLE
QUI-1359: Updating OTA public key

### PR DESCRIPTION
**Pull request by brian-quilt**

### CODE REVIEW

**Comment by brian-quilt** [comment]
We need to coordinate how we will merge and then roll out this new OTA signing key. I believe that the order of operations is as follows:
1. We update the firmware to include our new public key while still signing the OTA with the old private key. After doing this upgrade
2. Devices cannot take new FW OTAs until we begin signing images with the new OTA private key.
3. After all devices have updated to have the new public key, we can begin signing images with the new OTA private key
4. We deploy the OTA signed by the new key

**Comment by ZhenQuilt** [comment]
> We need to coordinate how we will merge and then roll out this new OTA signing key. I believe that the order of operations is as follows:
> 
> 1. We update the firmware to include our new public key while still signing the OTA with the old private key. After doing this upgrade
> 2. Devices cannot take new FW OTAs until we begin signing images with the new OTA private key.
> 3. After all devices have updated to have the new public key, we can begin signing images with the new OTA private key
> 4. We deploy the OTA signed by the new key


LGTM!

**Review by ZhenQuilt — APPROVED** [review]

**Comment by ZhenQuilt** [comment]
Remember to update the SHA in the build to point to this new commit

**Comment by brian-quilt** [comment]
> Remember to update the SHA in the build to point to this new commit

I'm not positive if that is necessary. We are referencing the branch, not a specific commit: https://github.com/QuiltAir/meta-quilt/blob/38e9e9ceee54fde542db115ebb817694095a5db8/.github/actions/firmware-build-action/action.yaml#L103C16-L103C39

Is there another place I need to update?

**Pull request merged**
